HTTP_PARAMS_LIST = [
    "AID",
    "AspxAutoDetectCookieSupport",
    "C",
    "CFID",
    "CFTOKEN",
    "CHANNEL",
    "CODE",
    "FID",
    "GI_ID",
    "ID",
    "Id",
    "Itemid",
    "L",
    "N",
    "O",
    "ObjectPath",
    "Open",
    "P",
    "PAGEN_1",
    "PS",
    "PUT",
    "Page",
    "R2",
    "ReturnUrl",
    "___from_store",
    "___store",
    "_action",
    "_bc_fsnf",
    "_bqG",
    "_bqH",
    "_method",
    "_ref",
    "_tags_limit",
    "_wpnonce",
    "a",
    "ac",
    "access",
    "account",
    "act",
    "action",
    "activity",
    "add",
    "add-to-cart",
    "add_acc",
    "add_cat",
    "add_comment",
    "add_event",
    "add_file",
    "add_rule",
    "add_site",
    "add_tag",
    "add_to_wishlist",
    "add_txt",
    "add_type",
    "add_user",
    "addurl",
    "adm",
    "admin",
    "advanced",
    "after",
    "age",
    "ai1ec",
    "aid",
    "ajax",
    "album",
    "alias",
    "allow",
    "allowed",
    "allowopts",
    "alpha",
    "alt",
    "alter",
    "amount",
    "amp",
    "ampday",
    "ampmonth",
    "ampyear",
    "api",
    "api_key",
    "app",
    "arch",
    "area",
    "arg",
    "args",
    "article",
    "asins",
    "at",
    "attachment_id",
    "auth",
    "authcfg",
    "authentication",
    "authlvl",
    "author",
    "author_id",
    "auto",
    "autoplay",
    "b",
    "back",
    "backurl",
    "before",
    "begindate",
    "bid",
    "bind",
    "block",
    "bo_table",
    "board",
    "board_no",
    "bonus",
    "bool",
    "boolean",
    "brand",
    "browse",
    "byte",
    "bytes",
    "c",
    "cHash",
    "cPath",
    "cache",
    "cad",
    "caid",
    "caldate",
    "call",
    "callback",
    "case",
    "cat",
    "cat_id",
    "cate_no",
    "category",
    "categoryId",
    "category_id",
    "categoryid",
    "catid",
    "cc",
    "cfg",
    "cgid",
    "char",
    "check",
    "checkout",
    "checkout_url",
    "cid",
    "city",
    "citycode",
    "cli",
    "client",
    "client_id",
    "clone",
    "cmd",
    "code",
    "collection",
    "collectionIds",
    "color",
    "column",
    "columns",
    "combine",
    "command",
    "comment",
    "compare",
    "conf",
    "config",
    "confirm",
    "content",
    "contenttype",
    "context",
    "continue",
    "controller",
    "count",
    "country",
    "counts",
    "coupon",
    "create",
    "creators",
    "csid",
    "csrf_token",
    "ct",
    "currency",
    "custom",
    "d",
    "daemon",
    "data",
    "date",
    "day",
    "days",
    "db",
    "dbg",
    "dbn",
    "dbname",
    "debug",
    "delete",
    "deleteUser",
    "department",
    "desc",
    "descending",
    "description",
    "dest",
    "destination",
    "detail",
    "did",
    "diff",
    "digest",
    "dir",
    "direction",
    "disable",
    "disabled",
    "display",
    "display_group",
    "dms",
    "do",
    "doc",
    "doc_id",
    "docid",
    "document",
    "document_srl",
    "domain",
    "download",
    "dq",
    "dummy",
    "e",
    "edit",
    "edition",
    "ei",
    "elementor_library",
    "email",
    "emailto",
    "enable",
    "enddate",
    "ends",
    "entity",
    "errmsg",
    "error",
    "errormsg",
    "errorstr",
    "etal",
    "event",
    "exe",
    "exec",
    "execute",
    "expand",
    "export",
    "ext",
    "extension",
    "f",
    "facet",
    "facets",
    "fallback",
    "family",
    "fbclid",
    "feature",
    "federated_search_id",
    "feed",
    "fetch",
    "fi",
    "fid",
    "field",
    "fields",
    "file",
    "file_name",
    "file_url",
    "filename",
    "filter",
    "filter_0",
    "filter_1",
    "filter_10",
    "filter_11",
    "filter_2",
    "filter_3",
    "filter_4",
    "filter_5",
    "filter_6",
    "filter_7",
    "filter_8",
    "filter_9",
    "filter_by",
    "filter_field_1",
    "filter_field_10",
    "filter_field_11",
    "filter_field_12",
    "filter_field_13",
    "filter_field_2",
    "filter_field_3",
    "filter_field_4",
    "filter_field_5",
    "filter_field_6",
    "filter_field_7",
    "filter_field_8",
    "filter_field_9",
    "filter_relational_operator",
    "filter_relational_operator_0",
    "filter_relational_operator_1",
    "filter_relational_operator_10",
    "filter_relational_operator_11",
    "filter_relational_operator_2",
    "filter_relational_operator_3",
    "filter_relational_operator_4",
    "filter_relational_operator_5",
    "filter_relational_operator_6",
    "filter_relational_operator_7",
    "filter_relational_operator_8",
    "filter_relational_operator_9",
    "filter_type_1",
    "filter_type_10",
    "filter_type_11",
    "filter_type_12",
    "filter_type_13",
    "filter_type_2",
    "filter_type_3",
    "filter_type_4",
    "filter_type_5",
    "filter_type_6",
    "filter_type_7",
    "filter_type_8",
    "filter_type_9",
    "filter_value_1",
    "filter_value_10",
    "filter_value_11",
    "filter_value_12",
    "filter_value_13",
    "filter_value_2",
    "filter_value_3",
    "filter_value_4",
    "filter_value_5",
    "filter_value_6",
    "filter_value_7",
    "filter_value_8",
    "filter_value_9",
    "filtername",
    "filterquery",
    "filters",
    "filtertype",
    "filtertype_0",
    "filtertype_1",
    "filtertype_10",
    "filtertype_11",
    "filtertype_2",
    "filtertype_3",
    "filtertype_4",
    "filtertype_5",
    "filtertype_6",
    "filtertype_7",
    "filtertype_8",
    "filtertype_9",
    "fl",
    "flag",
    "fn",
    "fname",
    "focus",
    "folder",
    "folder_url",
    "font",
    "force",
    "format",
    "forum",
    "forward",
    "fp",
    "fq",
    "fr",
    "fr2",
    "from",
    "from_url",
    "fromdate",
    "func",
    "function",
    "g",
    "gallery",
    "geo",
    "gid",
    "go",
    "goto",
    "grant",
    "group",
    "group_id",
    "groups",
    "h",
    "hash",
    "height",
    "hideanons",
    "hidebots",
    "hideliu",
    "hideminor",
    "hidemyself",
    "highlight",
    "hl",
    "host",
    "hour",
    "html",
    "i",
    "id",
    "id_product",
    "ids",
    "idx",
    "idxno",
    "ie",
    "image",
    "image_url",
    "img",
    "img_url",
    "immagine",
    "import",
    "in",
    "inc",
    "include",
    "index",
    "info",
    "init",
    "input",
    "inside",
    "instance",
    "inverse",
    "ip",
    "ipaddr",
    "is_logged",
    "isbn",
    "islandora_solr_search_navigation",
    "ispublic",
    "item",
    "itemid",
    "items_per_page",
    "j",
    "job",
    "json",
    "jsonp",
    "jump",
    "k",
    "key",
    "keyword",
    "keywords",
    "kind",
    "kw",
    "l",
    "label",
    "labels",
    "lang",
    "language",
    "lat",
    "layout",
    "leave",
    "len",
    "length",
    "letter",
    "level",
    "levels",
    "license_id",
    "lid",
    "lightbox",
    "like_comment",
    "limit",
    "link",
    "list",
    "listStyle",
    "list_type",
    "lng",
    "load",
    "load_file",
    "load_url",
    "loc",
    "locale",
    "locale-attribute",
    "locate",
    "location",
    "log",
    "login",
    "login_url",
    "logout",
    "lon",
    "lookfor",
    "lr",
    "lvl",
    "m",
    "main_page",
    "make",
    "manualLanguageChange",
    "manufacturer",
    "map",
    "max",
    "maximum",
    "maxlen",
    "media",
    "medio",
    "menu",
    "method",
    "mid",
    "min",
    "mini",
    "minimum",
    "minute",
    "mod",
    "modal",
    "mode",
    "model",
    "modify",
    "module",
    "month",
    "msg",
    "n",
    "name",
    "names",
    "navigation",
    "neighborhood",
    "next",
    "next_page",
    "nid",
    "no",
    "no_cache",
    "no_renew",
    "nocache",
    "nofollow",
    "nonce",
    "ns",
    "null",
    "num",
    "number",
    "o",
    "object",
    "offset",
    "oid",
    "oldid",
    "op",
    "open",
    "operator",
    "option",
    "ord",
    "order",
    "order_by",
    "order_type",
    "orderby",
    "ordering",
    "org",
    "organization",
    "origin",
    "osCsid",
    "out",
    "output",
    "p",
    "p_auth",
    "p_p_col_count",
    "p_p_col_id",
    "p_p_id",
    "p_p_lifecycle",
    "p_p_mode",
    "p_p_state",
    "pag",
    "page",
    "pageId",
    "pageSize",
    "page_id",
    "page_url",
    "paged",
    "pageid",
    "pagina",
    "param",
    "params",
    "part",
    "password",
    "path",
    "payload",
    "pdf",
    "per",
    "per_page",
    "person",
    "pg",
    "php_path",
    "pid",
    "ping",
    "places",
    "platform",
    "plugin",
    "port",
    "pos",
    "position",
    "post",
    "post_id",
    "post_type",
    "postcount",
    "power",
    "pp",
    "pref",
    "prefix",
    "prefn1",
    "prefn2",
    "prefv1",
    "prefv2",
    "prepare",
    "prev",
    "preview",
    "previous_page_section_name",
    "price",
    "print",
    "printable",
    "process",
    "prod_id",
    "product",
    "product_count",
    "product_id",
    "product_no",
    "product_order",
    "product_orderby",
    "product_sort",
    "product_type",
    "product_view",
    "products_id",
    "profile",
    "promo_code",
    "provider",
    "ps",
    "publicationYear",
    "q",
    "qf",
    "qid",
    "qty",
    "quantity",
    "query",
    "quote",
    "r",
    "range",
    "range_end",
    "range_start",
    "rank",
    "ranking",
    "rate",
    "rating",
    "reaction",
    "read",
    "recor",
    "redir",
    "redirect",
    "redirect_to",
    "redirect_uri",
    "redirect_url",
    "redlink",
    "ref",
    "reference",
    "referer",
    "referrer",
    "refurl",
    "reg",
    "regex",
    "regexp",
    "region",
    "rename",
    "render",
    "reply",
    "replytocom",
    "report",
    "req",
    "res",
    "res_format",
    "reset",
    "response_type",
    "results",
    "retpath",
    "return",
    "returnTo",
    "returnUrl",
    "return_path",
    "return_to",
    "return_url",
    "returnto",
    "returntoquery",
    "returnurl",
    "rev",
    "revision",
    "rid",
    "role",
    "room",
    "root",
    "route",
    "row",
    "rows",
    "rpp",
    "rss",
    "rt",
    "run",
    "rurl",
    "s",
    "sa",
    "sale_date",
    "sc",
    "scope",
    "script",
    "sd",
    "search",
    "search_field",
    "search_type",
    "searchfilter",
    "searchid",
    "section",
    "sector",
    "security",
    "sel",
    "select",
    "selected_facets",
    "selected_filters",
    "sequence",
    "service",
    "session",
    "set",
    "sf_culture",
    "share",
    "shared",
    "shell",
    "show",
    "showComment",
    "showtopic",
    "site",
    "size",
    "sku",
    "sleep",
    "smode",
    "sort",
    "sortBy",
    "sortDir",
    "sort_by",
    "sort_index",
    "sort_key",
    "sort_order",
    "sortby",
    "sorting",
    "source",
    "source_id",
    "sp",
    "special",
    "sr",
    "src",
    "sso",
    "st",
    "star",
    "start",
    "starts_with",
    "state",
    "status",
    "step",
    "stop",
    "strict",
    "string",
    "style",
    "sub",
    "subcat",
    "subject",
    "subjects",
    "submit",
    "subscribe",
    "symbol",
    "sys",
    "t",
    "tab",
    "tab_details",
    "tab_files",
    "table",
    "tag",
    "tags",
    "target",
    "task",
    "tbn",
    "temp",
    "template",
    "term",
    "terms",
    "test",
    "testing",
    "text",
    "theme",
    "thread",
    "tid",
    "time",
    "timestamp",
    "tipo",
    "title",
    "tld",
    "tmp",
    "tmpl",
    "to",
    "todate",
    "toggle",
    "toggleopen",
    "token",
    "topLod",
    "topic",
    "tree",
    "type",
    "type_id",
    "u",
    "uid",
    "unsubscribe_token",
    "update",
    "upload",
    "uri",
    "url",
    "used",
    "user",
    "user_id",
    "userid",
    "username",
    "utm_campaign",
    "utm_content",
    "utm_medium",
    "utm_source",
    "utm_term",
    "utmi_p",
    "uuid",
    "v",
    "val",
    "validate",
    "value",
    "var",
    "variant",
    "ver",
    "version",
    "vid",
    "view",
    "view_all",
    "view_type",
    "volume",
    "vq",
    "w",
    "where",
    "widgetId",
    "widgetType",
    "width",
    "window",
    "withdraw",
    "word",
    "worker",
    "workerId",
    "wr_id",
    "write",
    "x",
    "xargs",
    "xdebug",
    "xhr",
    "xml",
    "y",
    "year",
    "yr",
    "z",
    "zip",
    "zoom",
]

CHAR_PATTERNS = {
    "dict|e|list|batch(INDEX)|first|last": {
        "1": "&",
        "2": "l",
        "3": "t",
        "4": ";",
        "5": "c",
        "6": "l",
        "7": "a",
        "8": "s",
        "9": "s",
        "10": " ",
        "11": "&",
        "12": "#",
        "13": "3",
        "14": "9",
        "15": ";",
        "16": "d",
        "17": "i",
        "18": "c",
        "19": "t",
        "20": "&",
        "21": "#",
        "22": "3",
        "23": "9",
        "24": ";",
        "25": "&",
        "26": "g",
        "27": "t",
        "28": ";",
        "29": ";",
        "30": ";",
    },
    "(dict|e|list)[INDEX]": {
        "0": "&",
        "1": "l",
        "2": "t",
        "3": ";",
        "4": "c",
        "5": "l",
        "6": "a",
        "7": "s",
        "8": "s",
        "9": " ",
        "10": "&",
        "11": "#",
        "12": "3",
        "13": "9",
        "14": ";",
        "15": "d",
        "16": "i",
        "17": "c",
        "18": "t",
        "19": "&",
        "20": "#",
        "21": "3",
        "22": "9",
        "23": ";",
        "24": "&",
        "25": "g",
        "26": "t",
        "27": ";",
    },
    "dict|string|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "d",
        "10": "i",
        "11": "c",
        "12": "t",
        "13": "'",
        "14": ">",
        "15": ">",
        "16": ">",
    },
    "(dict|string|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "d",
        "9": "i",
        "10": "c",
        "11": "t",
        "12": "'",
        "13": ">",
    },
    "dict|pprint|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "d",
        "10": "i",
        "11": "c",
        "12": "t",
        "13": "'",
        "14": ">",
        "15": ">",
        "16": ">",
    },
    "(dict|pprint|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "d",
        "9": "i",
        "10": "c",
        "11": "t",
        "12": "'",
        "13": ">",
    },
    "dict|safe|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "d",
        "10": "i",
        "11": "c",
        "12": "t",
        "13": "'",
        "14": ">",
        "15": ">",
        "16": ">",
    },
    "(dict|safe|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "d",
        "9": "i",
        "10": "c",
        "11": "t",
        "12": "'",
        "13": ">",
    },
    "dict|truncate|list|batch(INDEX)|first|last": {},
    "(dict|truncate|list)[INDEX]": {},
    "dict|lower|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "d",
        "10": "i",
        "11": "c",
        "12": "t",
        "13": "'",
        "14": ">",
        "15": ">",
        "16": ">",
    },
    "(dict|lower|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "d",
        "9": "i",
        "10": "c",
        "11": "t",
        "12": "'",
        "13": ">",
    },
    "lipsum|e|list|batch(INDEX)|first|last": {
        "1": "&",
        "2": "l",
        "3": "t",
        "4": ";",
        "5": "f",
        "6": "u",
        "7": "n",
        "8": "c",
        "9": "t",
        "10": "i",
        "11": "o",
        "12": "n",
        "13": " ",
        "14": "g",
        "15": "e",
        "16": "n",
        "17": "e",
        "18": "r",
        "19": "a",
        "20": "t",
    },
    "(lipsum|e|list)[INDEX]": {
        "0": "&",
        "1": "l",
        "2": "t",
        "3": ";",
        "4": "f",
        "5": "u",
        "6": "n",
        "7": "c",
        "8": "t",
        "9": "i",
        "10": "o",
        "11": "n",
        "12": " ",
        "13": "g",
        "14": "e",
        "15": "n",
        "16": "e",
        "17": "r",
        "18": "a",
        "19": "t",
    },
    "lipsum|string|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "f",
        "3": "u",
        "4": "n",
        "5": "c",
        "6": "t",
        "7": "i",
        "8": "o",
        "9": "n",
        "10": " ",
        "11": "g",
        "12": "e",
        "13": "n",
        "14": "e",
        "15": "r",
        "16": "a",
        "17": "t",
    },
    "(lipsum|string|list)[INDEX]": {
        "0": "<",
        "1": "f",
        "2": "u",
        "3": "n",
        "4": "c",
        "5": "t",
        "6": "i",
        "7": "o",
        "8": "n",
        "9": " ",
        "10": "g",
        "11": "e",
        "12": "n",
        "13": "e",
        "14": "r",
        "15": "a",
        "16": "t",
    },
    "lipsum|pprint|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "f",
        "3": "u",
        "4": "n",
        "5": "c",
        "6": "t",
        "7": "i",
        "8": "o",
        "9": "n",
        "10": " ",
        "11": "g",
        "12": "e",
        "13": "n",
        "14": "e",
        "15": "r",
        "16": "a",
        "17": "t",
    },
    "(lipsum|pprint|list)[INDEX]": {
        "0": "<",
        "1": "f",
        "2": "u",
        "3": "n",
        "4": "c",
        "5": "t",
        "6": "i",
        "7": "o",
        "8": "n",
        "9": " ",
        "10": "g",
        "11": "e",
        "12": "n",
        "13": "e",
        "14": "r",
        "15": "a",
        "16": "t",
    },
    "lipsum|safe|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "f",
        "3": "u",
        "4": "n",
        "5": "c",
        "6": "t",
        "7": "i",
        "8": "o",
        "9": "n",
        "10": " ",
        "11": "g",
        "12": "e",
        "13": "n",
        "14": "e",
        "15": "r",
        "16": "a",
        "17": "t",
    },
    "(lipsum|safe|list)[INDEX]": {
        "0": "<",
        "1": "f",
        "2": "u",
        "3": "n",
        "4": "c",
        "5": "t",
        "6": "i",
        "7": "o",
        "8": "n",
        "9": " ",
        "10": "g",
        "11": "e",
        "12": "n",
        "13": "e",
        "14": "r",
        "15": "a",
        "16": "t",
    },
    "lipsum|truncate|list|batch(INDEX)|first|last": {},
    "(lipsum|truncate|list)[INDEX]": {},
    "lipsum|lower|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "f",
        "3": "u",
        "4": "n",
        "5": "c",
        "6": "t",
        "7": "i",
        "8": "o",
        "9": "n",
        "10": " ",
        "11": "g",
        "12": "e",
        "13": "n",
        "14": "e",
        "15": "r",
        "16": "a",
        "17": "t",
    },
    "(lipsum|lower|list)[INDEX]": {
        "0": "<",
        "1": "f",
        "2": "u",
        "3": "n",
        "4": "c",
        "5": "t",
        "6": "i",
        "7": "o",
        "8": "n",
        "9": " ",
        "10": "g",
        "11": "e",
        "12": "n",
        "13": "e",
        "14": "r",
        "15": "a",
        "16": "t",
    },
    "{}|e|list|batch(INDEX)|first|last": {
        "1": "{",
        "2": "}",
        "3": "}",
        "4": "}",
        "5": "}",
        "6": "}",
        "7": "}",
        "8": "}",
        "9": "}",
        "10": "}",
        "11": "}",
    },
    "({}|e|list)[INDEX]": {"0": "{", "1": "}"},
    "{}|string|list|batch(INDEX)|first|last": {
        "1": "{",
        "2": "}",
        "3": "}",
        "4": "}",
        "5": "}",
        "6": "}",
        "7": "}",
        "8": "}",
        "9": "}",
        "10": "}",
        "11": "}",
    },
    "({}|string|list)[INDEX]": {"0": "{", "1": "}"},
    "{}|pprint|list|batch(INDEX)|first|last": {
        "1": "{",
        "2": "}",
        "3": "}",
        "4": "}",
        "5": "}",
        "6": "}",
        "7": "}",
        "8": "}",
        "9": "}",
        "10": "}",
        "11": "}",
    },
    "({}|pprint|list)[INDEX]": {"0": "{", "1": "}"},
    "{}|safe|list|batch(INDEX)|first|last": {
        "1": "{",
        "2": "}",
        "3": "}",
        "4": "}",
        "5": "}",
        "6": "}",
        "7": "}",
        "8": "}",
        "9": "}",
        "10": "}",
        "11": "}",
    },
    "({}|safe|list)[INDEX]": {"0": "{", "1": "}"},
    "{}|truncate|list|batch(INDEX)|first|last": {},
    "({}|truncate|list)[INDEX]": {},
    "{}|lower|list|batch(INDEX)|first|last": {
        "1": "{",
        "2": "}",
        "3": "}",
        "4": "}",
        "5": "}",
        "6": "}",
        "7": "}",
        "8": "}",
        "9": "}",
        "10": "}",
        "11": "}",
    },
    "({}|lower|list)[INDEX]": {"0": "{", "1": "}"},
    "()|e|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": ")",
        "3": ")",
        "4": ")",
        "5": ")",
        "6": ")",
        "7": ")",
        "8": ")",
        "9": ")",
        "10": ")",
        "11": ")",
    },
    "(()|e|list)[INDEX]": {"0": "(", "1": ")"},
    "()|string|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": ")",
        "3": ")",
        "4": ")",
        "5": ")",
        "6": ")",
        "7": ")",
        "8": ")",
        "9": ")",
        "10": ")",
        "11": ")",
    },
    "(()|string|list)[INDEX]": {"0": "(", "1": ")"},
    "()|pprint|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": ")",
        "3": ")",
        "4": ")",
        "5": ")",
        "6": ")",
        "7": ")",
        "8": ")",
        "9": ")",
        "10": ")",
        "11": ")",
    },
    "(()|pprint|list)[INDEX]": {"0": "(", "1": ")"},
    "()|safe|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": ")",
        "3": ")",
        "4": ")",
        "5": ")",
        "6": ")",
        "7": ")",
        "8": ")",
        "9": ")",
        "10": ")",
        "11": ")",
    },
    "(()|safe|list)[INDEX]": {"0": "(", "1": ")"},
    "()|truncate|list|batch(INDEX)|first|last": {},
    "(()|truncate|list)[INDEX]": {},
    "()|lower|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": ")",
        "3": ")",
        "4": ")",
        "5": ")",
        "6": ")",
        "7": ")",
        "8": ")",
        "9": ")",
        "10": ")",
        "11": ")",
    },
    "(()|lower|list)[INDEX]": {"0": "(", "1": ")"},
    "(xn,)|e|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": "U",
        "3": "n",
        "4": "d",
        "5": "e",
        "6": "f",
        "7": "i",
        "8": "n",
        "9": "e",
        "10": "d",
        "11": ",",
        "12": ")",
        "13": ")",
        "14": ")",
    },
    "((xn,)|e|list)[INDEX]": {
        "0": "(",
        "1": "U",
        "2": "n",
        "3": "d",
        "4": "e",
        "5": "f",
        "6": "i",
        "7": "n",
        "8": "e",
        "9": "d",
        "10": ",",
        "11": ")",
    },
    "(xn,)|string|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": "U",
        "3": "n",
        "4": "d",
        "5": "e",
        "6": "f",
        "7": "i",
        "8": "n",
        "9": "e",
        "10": "d",
        "11": ",",
        "12": ")",
        "13": ")",
        "14": ")",
    },
    "((xn,)|string|list)[INDEX]": {
        "0": "(",
        "1": "U",
        "2": "n",
        "3": "d",
        "4": "e",
        "5": "f",
        "6": "i",
        "7": "n",
        "8": "e",
        "9": "d",
        "10": ",",
        "11": ")",
    },
    "(xn,)|pprint|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": "U",
        "3": "n",
        "4": "d",
        "5": "e",
        "6": "f",
        "7": "i",
        "8": "n",
        "9": "e",
        "10": "d",
        "11": ",",
        "12": ")",
        "13": ")",
        "14": ")",
    },
    "((xn,)|pprint|list)[INDEX]": {
        "0": "(",
        "1": "U",
        "2": "n",
        "3": "d",
        "4": "e",
        "5": "f",
        "6": "i",
        "7": "n",
        "8": "e",
        "9": "d",
        "10": ",",
        "11": ")",
    },
    "(xn,)|safe|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": "U",
        "3": "n",
        "4": "d",
        "5": "e",
        "6": "f",
        "7": "i",
        "8": "n",
        "9": "e",
        "10": "d",
        "11": ",",
        "12": ")",
        "13": ")",
        "14": ")",
    },
    "((xn,)|safe|list)[INDEX]": {
        "0": "(",
        "1": "U",
        "2": "n",
        "3": "d",
        "4": "e",
        "5": "f",
        "6": "i",
        "7": "n",
        "8": "e",
        "9": "d",
        "10": ",",
        "11": ")",
    },
    "(xn,)|truncate|list|batch(INDEX)|first|last": {},
    "((xn,)|truncate|list)[INDEX]": {},
    "(xn,)|lower|list|batch(INDEX)|first|last": {
        "1": "(",
        "2": "u",
        "3": "n",
        "4": "d",
        "5": "e",
        "6": "f",
        "7": "i",
        "8": "n",
        "9": "e",
        "10": "d",
        "11": ",",
        "12": ")",
        "13": ")",
        "14": ")",
    },
    "((xn,)|lower|list)[INDEX]": {
        "0": "(",
        "1": "u",
        "2": "n",
        "3": "d",
        "4": "e",
        "5": "f",
        "6": "i",
        "7": "n",
        "8": "e",
        "9": "d",
        "10": ",",
        "11": ")",
    },
    "cycler.__name__|e|list|batch(INDEX)|first|last": {
        "1": "C",
        "2": "y",
        "3": "c",
        "4": "l",
        "5": "e",
        "6": "r",
        "7": "r",
        "8": "r",
        "9": "r",
        "10": "r",
        "11": "r",
    },
    "(cycler.__name__|e|list)[INDEX]": {
        "0": "C",
        "1": "y",
        "2": "c",
        "3": "l",
        "4": "e",
        "5": "r",
    },
    "cycler.__name__|string|list|batch(INDEX)|first|last": {
        "1": "C",
        "2": "y",
        "3": "c",
        "4": "l",
        "5": "e",
        "6": "r",
        "7": "r",
        "8": "r",
        "9": "r",
        "10": "r",
        "11": "r",
    },
    "(cycler.__name__|string|list)[INDEX]": {
        "0": "C",
        "1": "y",
        "2": "c",
        "3": "l",
        "4": "e",
        "5": "r",
    },
    "cycler.__name__|pprint|list|batch(INDEX)|first|last": {
        "1": "'",
        "2": "C",
        "3": "y",
        "4": "c",
        "5": "l",
        "6": "e",
        "7": "r",
        "8": "'",
        "9": "'",
        "10": "'",
        "11": "'",
    },
    "(cycler.__name__|pprint|list)[INDEX]": {
        "0": "'",
        "1": "C",
        "2": "y",
        "3": "c",
        "4": "l",
        "5": "e",
        "6": "r",
        "7": "'",
    },
    "cycler.__name__|safe|list|batch(INDEX)|first|last": {
        "1": "C",
        "2": "y",
        "3": "c",
        "4": "l",
        "5": "e",
        "6": "r",
        "7": "r",
        "8": "r",
        "9": "r",
        "10": "r",
        "11": "r",
    },
    "(cycler.__name__|safe|list)[INDEX]": {
        "0": "C",
        "1": "y",
        "2": "c",
        "3": "l",
        "4": "e",
        "5": "r",
    },
    "cycler.__name__|truncate|list|batch(INDEX)|first|last": {
        "1": "C",
        "2": "y",
        "3": "c",
        "4": "l",
        "5": "e",
        "6": "r",
        "7": "r",
        "8": "r",
        "9": "r",
        "10": "r",
        "11": "r",
    },
    "(cycler.__name__|truncate|list)[INDEX]": {
        "0": "C",
        "1": "y",
        "2": "c",
        "3": "l",
        "4": "e",
        "5": "r",
    },
    "cycler.__name__|lower|list|batch(INDEX)|first|last": {
        "1": "c",
        "2": "y",
        "3": "c",
        "4": "l",
        "5": "e",
        "6": "r",
        "7": "r",
        "8": "r",
        "9": "r",
        "10": "r",
        "11": "r",
    },
    "(cycler.__name__|lower|list)[INDEX]": {
        "0": "c",
        "1": "y",
        "2": "c",
        "3": "l",
        "4": "e",
        "5": "r",
    },
    "cycler|e|list|batch(INDEX)|first|last": {
        "1": "&",
        "2": "l",
        "3": "t",
        "4": ";",
        "5": "c",
        "6": "l",
        "7": "a",
        "8": "s",
        "9": "s",
        "10": " ",
        "11": "&",
        "12": "#",
        "13": "3",
        "14": "9",
        "15": ";",
        "16": "j",
        "17": "i",
        "18": "n",
        "19": "j",
        "20": "a",
        "21": "2",
        "22": ".",
        "23": "u",
        "24": "t",
        "25": "i",
        "26": "l",
        "27": "s",
        "28": ".",
        "29": "C",
        "30": "y",
        "31": "c",
        "32": "l",
        "33": "e",
        "34": "r",
        "35": "&",
        "36": "#",
        "37": "3",
        "38": "9",
        "39": ";",
        "40": "&",
        "41": "g",
        "42": "t",
        "43": ";",
        "44": ";",
        "45": ";",
    },
    "(cycler|e|list)[INDEX]": {
        "0": "&",
        "1": "l",
        "2": "t",
        "3": ";",
        "4": "c",
        "5": "l",
        "6": "a",
        "7": "s",
        "8": "s",
        "9": " ",
        "10": "&",
        "11": "#",
        "12": "3",
        "13": "9",
        "14": ";",
        "15": "j",
        "16": "i",
        "17": "n",
        "18": "j",
        "19": "a",
        "20": "2",
        "21": ".",
        "22": "u",
        "23": "t",
        "24": "i",
        "25": "l",
        "26": "s",
        "27": ".",
        "28": "C",
        "29": "y",
        "30": "c",
        "31": "l",
        "32": "e",
        "33": "r",
        "34": "&",
        "35": "#",
        "36": "3",
        "37": "9",
        "38": ";",
        "39": "&",
        "40": "g",
        "41": "t",
        "42": ";",
    },
    "cycler|string|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "j",
        "10": "i",
        "11": "n",
        "12": "j",
        "13": "a",
        "14": "2",
        "15": ".",
        "16": "u",
        "17": "t",
        "18": "i",
        "19": "l",
        "20": "s",
        "21": ".",
        "22": "C",
        "23": "y",
        "24": "c",
        "25": "l",
        "26": "e",
        "27": "r",
        "28": "'",
        "29": ">",
        "30": ">",
        "31": ">",
    },
    "(cycler|string|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "j",
        "9": "i",
        "10": "n",
        "11": "j",
        "12": "a",
        "13": "2",
        "14": ".",
        "15": "u",
        "16": "t",
        "17": "i",
        "18": "l",
        "19": "s",
        "20": ".",
        "21": "C",
        "22": "y",
        "23": "c",
        "24": "l",
        "25": "e",
        "26": "r",
        "27": "'",
        "28": ">",
    },
    "cycler|pprint|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "j",
        "10": "i",
        "11": "n",
        "12": "j",
        "13": "a",
        "14": "2",
        "15": ".",
        "16": "u",
        "17": "t",
        "18": "i",
        "19": "l",
        "20": "s",
        "21": ".",
        "22": "C",
        "23": "y",
        "24": "c",
        "25": "l",
        "26": "e",
        "27": "r",
        "28": "'",
        "29": ">",
        "30": ">",
        "31": ">",
    },
    "(cycler|pprint|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "j",
        "9": "i",
        "10": "n",
        "11": "j",
        "12": "a",
        "13": "2",
        "14": ".",
        "15": "u",
        "16": "t",
        "17": "i",
        "18": "l",
        "19": "s",
        "20": ".",
        "21": "C",
        "22": "y",
        "23": "c",
        "24": "l",
        "25": "e",
        "26": "r",
        "27": "'",
        "28": ">",
    },
    "cycler|safe|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "j",
        "10": "i",
        "11": "n",
        "12": "j",
        "13": "a",
        "14": "2",
        "15": ".",
        "16": "u",
        "17": "t",
        "18": "i",
        "19": "l",
        "20": "s",
        "21": ".",
        "22": "C",
        "23": "y",
        "24": "c",
        "25": "l",
        "26": "e",
        "27": "r",
        "28": "'",
        "29": ">",
        "30": ">",
        "31": ">",
    },
    "(cycler|safe|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "j",
        "9": "i",
        "10": "n",
        "11": "j",
        "12": "a",
        "13": "2",
        "14": ".",
        "15": "u",
        "16": "t",
        "17": "i",
        "18": "l",
        "19": "s",
        "20": ".",
        "21": "C",
        "22": "y",
        "23": "c",
        "24": "l",
        "25": "e",
        "26": "r",
        "27": "'",
        "28": ">",
    },
    "cycler|truncate|list|batch(INDEX)|first|last": {},
    "(cycler|truncate|list)[INDEX]": {},
    "cycler|lower|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "j",
        "10": "i",
        "11": "n",
        "12": "j",
        "13": "a",
        "14": "2",
        "15": ".",
        "16": "u",
        "17": "t",
        "18": "i",
        "19": "l",
        "20": "s",
        "21": ".",
        "22": "c",
        "23": "y",
        "24": "c",
        "25": "l",
        "26": "e",
        "27": "r",
        "28": "'",
        "29": ">",
        "30": ">",
        "31": ">",
    },
    "(cycler|lower|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "j",
        "9": "i",
        "10": "n",
        "11": "j",
        "12": "a",
        "13": "2",
        "14": ".",
        "15": "u",
        "16": "t",
        "17": "i",
        "18": "l",
        "19": "s",
        "20": ".",
        "21": "c",
        "22": "y",
        "23": "c",
        "24": "l",
        "25": "e",
        "26": "r",
        "27": "'",
        "28": ">",
    },
    "namespace|e|list|batch(INDEX)|first|last": {
        "1": "&",
        "2": "l",
        "3": "t",
        "4": ";",
        "5": "c",
        "6": "l",
        "7": "a",
        "8": "s",
        "9": "s",
        "10": " ",
        "11": "&",
        "12": "#",
        "13": "3",
        "14": "9",
        "15": ";",
        "16": "j",
        "17": "i",
        "18": "n",
        "19": "j",
        "20": "a",
        "21": "2",
        "22": ".",
        "23": "u",
        "24": "t",
        "25": "i",
        "26": "l",
        "27": "s",
        "28": ".",
        "29": "N",
        "30": "a",
        "31": "m",
        "32": "e",
        "33": "s",
        "34": "p",
        "35": "a",
        "36": "c",
        "37": "e",
        "38": "&",
        "39": "#",
        "40": "3",
        "41": "9",
        "42": ";",
        "43": "&",
        "44": "g",
        "45": "t",
        "46": ";",
        "47": ";",
        "48": ";",
    },
    "(namespace|e|list)[INDEX]": {
        "0": "&",
        "1": "l",
        "2": "t",
        "3": ";",
        "4": "c",
        "5": "l",
        "6": "a",
        "7": "s",
        "8": "s",
        "9": " ",
        "10": "&",
        "11": "#",
        "12": "3",
        "13": "9",
        "14": ";",
        "15": "j",
        "16": "i",
        "17": "n",
        "18": "j",
        "19": "a",
        "20": "2",
        "21": ".",
        "22": "u",
        "23": "t",
        "24": "i",
        "25": "l",
        "26": "s",
        "27": ".",
        "28": "N",
        "29": "a",
        "30": "m",
        "31": "e",
        "32": "s",
        "33": "p",
        "34": "a",
        "35": "c",
        "36": "e",
        "37": "&",
        "38": "#",
        "39": "3",
        "40": "9",
        "41": ";",
        "42": "&",
        "43": "g",
        "44": "t",
        "45": ";",
    },
    "namespace|string|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "j",
        "10": "i",
        "11": "n",
        "12": "j",
        "13": "a",
        "14": "2",
        "15": ".",
        "16": "u",
        "17": "t",
        "18": "i",
        "19": "l",
        "20": "s",
        "21": ".",
        "22": "N",
        "23": "a",
        "24": "m",
        "25": "e",
        "26": "s",
        "27": "p",
        "28": "a",
        "29": "c",
        "30": "e",
        "31": "'",
        "32": ">",
        "33": ">",
        "34": ">",
    },
    "(namespace|string|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "j",
        "9": "i",
        "10": "n",
        "11": "j",
        "12": "a",
        "13": "2",
        "14": ".",
        "15": "u",
        "16": "t",
        "17": "i",
        "18": "l",
        "19": "s",
        "20": ".",
        "21": "N",
        "22": "a",
        "23": "m",
        "24": "e",
        "25": "s",
        "26": "p",
        "27": "a",
        "28": "c",
        "29": "e",
        "30": "'",
        "31": ">",
    },
    "namespace|pprint|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "j",
        "10": "i",
        "11": "n",
        "12": "j",
        "13": "a",
        "14": "2",
        "15": ".",
        "16": "u",
        "17": "t",
        "18": "i",
        "19": "l",
        "20": "s",
        "21": ".",
        "22": "N",
        "23": "a",
        "24": "m",
        "25": "e",
        "26": "s",
        "27": "p",
        "28": "a",
        "29": "c",
        "30": "e",
        "31": "'",
        "32": ">",
        "33": ">",
        "34": ">",
    },
    "(namespace|pprint|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "j",
        "9": "i",
        "10": "n",
        "11": "j",
        "12": "a",
        "13": "2",
        "14": ".",
        "15": "u",
        "16": "t",
        "17": "i",
        "18": "l",
        "19": "s",
        "20": ".",
        "21": "N",
        "22": "a",
        "23": "m",
        "24": "e",
        "25": "s",
        "26": "p",
        "27": "a",
        "28": "c",
        "29": "e",
        "30": "'",
        "31": ">",
    },
    "namespace|safe|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "j",
        "10": "i",
        "11": "n",
        "12": "j",
        "13": "a",
        "14": "2",
        "15": ".",
        "16": "u",
        "17": "t",
        "18": "i",
        "19": "l",
        "20": "s",
        "21": ".",
        "22": "N",
        "23": "a",
        "24": "m",
        "25": "e",
        "26": "s",
        "27": "p",
        "28": "a",
        "29": "c",
        "30": "e",
        "31": "'",
        "32": ">",
        "33": ">",
        "34": ">",
    },
    "(namespace|safe|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "j",
        "9": "i",
        "10": "n",
        "11": "j",
        "12": "a",
        "13": "2",
        "14": ".",
        "15": "u",
        "16": "t",
        "17": "i",
        "18": "l",
        "19": "s",
        "20": ".",
        "21": "N",
        "22": "a",
        "23": "m",
        "24": "e",
        "25": "s",
        "26": "p",
        "27": "a",
        "28": "c",
        "29": "e",
        "30": "'",
        "31": ">",
    },
    "namespace|truncate|list|batch(INDEX)|first|last": {},
    "(namespace|truncate|list)[INDEX]": {},
    "namespace|lower|list|batch(INDEX)|first|last": {
        "1": "<",
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "j",
        "10": "i",
        "11": "n",
        "12": "j",
        "13": "a",
        "14": "2",
        "15": ".",
        "16": "u",
        "17": "t",
        "18": "i",
        "19": "l",
        "20": "s",
        "21": ".",
        "22": "n",
        "23": "a",
        "24": "m",
        "25": "e",
        "26": "s",
        "27": "p",
        "28": "a",
        "29": "c",
        "30": "e",
        "31": "'",
        "32": ">",
        "33": ">",
        "34": ">",
    },
    "(namespace|lower|list)[INDEX]": {
        "0": "<",
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "j",
        "9": "i",
        "10": "n",
        "11": "j",
        "12": "a",
        "13": "2",
        "14": ".",
        "15": "u",
        "16": "t",
        "17": "i",
        "18": "l",
        "19": "s",
        "20": ".",
        "21": "n",
        "22": "a",
        "23": "m",
        "24": "e",
        "25": "s",
        "26": "p",
        "27": "a",
        "28": "c",
        "29": "e",
        "30": "'",
        "31": ">",
    },
    "(dict|trim|list)[INDEX]": {
        "1": "c",
        "2": "l",
        "3": "a",
        "4": "s",
        "5": "s",
        "6": " ",
        "7": "'",
        "8": "d",
        "9": "i",
        "10": "c",
        "11": "t",
    },
    "dict|trim|list|batch(INDEX)|first|last": {
        "2": "c",
        "3": "l",
        "4": "a",
        "5": "s",
        "6": "s",
        "7": " ",
        "8": "'",
        "9": "d",
        "10": "i",
        "11": "c",
        "12": "t",
    },
    "({}|select()|trim|list)[INDEX]": {
        "1": "g",
        "2": "e",
        "3": "n",
        "4": "e",
        "5": "r",
        "6": "a",
        "7": "t",
        "8": "o",
        "9": "r",
        "10": " ",
        "11": "o",
        "12": "b",
        "13": "j",
        "14": "e",
        "15": "c",
        "16": "t",
        "17": " ",
        "18": "s",
        "19": "e",
        "20": "l",
        "21": "e",
        "22": "c",
        "23": "t",
        "24": "_",
        "25": "o",
        "26": "r",
        "27": "_",
        "28": "r",
        "29": "e",
        "30": "j",
        "31": "e",
        "32": "c",
        "33": "t",
        "34": " ",
        "35": "a",
        "36": "t",
    },
    "{}|select()|trim|list|batch(INDEX)|first|last": {
        "2": "g",
        "3": "e",
        "4": "n",
        "5": "e",
        "6": "r",
        "7": "a",
        "8": "t",
        "9": "o",
        "10": "r",
        "11": " ",
        "12": "o",
        "13": "b",
        "14": "j",
        "15": "e",
        "16": "c",
        "17": "t",
        "18": " ",
        "19": "s",
        "20": "e",
        "21": "l",
        "22": "e",
        "23": "c",
        "24": "t",
        "25": "_",
        "26": "o",
        "27": "r",
        "28": "_",
        "29": "r",
        "30": "e",
        "31": "j",
        "32": "e",
        "33": "c",
        "34": "t",
        "35": " ",
        "36": "a",
        "37": "t",
    },
    "(lipsum|trim|list)[INDEX]": {
        "1": "f",
        "2": "u",
        "3": "n",
        "4": "c",
        "5": "t",
        "6": "i",
        "7": "o",
        "8": "n",
        "9": " ",
        "10": "g",
        "11": "e",
        "12": "n",
        "13": "e",
        "14": "r",
        "15": "a",
        "16": "t",
        "17": "e",
        "18": "_",
        "19": "l",
        "20": "o",
        "21": "r",
        "22": "e",
        "23": "m",
        "24": "_",
        "25": "i",
        "26": "p",
        "27": "s",
        "28": "u",
        "29": "m",
        "30": " ",
        "31": "a",
        "32": "t",
        "33": " ",
        "34": "0",
        "35": "x",
        "36": "7",
    },
    "lipsum|trim|list|batch(INDEX)|first|last": {
        "2": "f",
        "3": "u",
        "4": "n",
        "5": "c",
        "6": "t",
        "7": "i",
        "8": "o",
        "9": "n",
        "10": " ",
        "11": "g",
        "12": "e",
        "13": "n",
        "14": "e",
        "15": "r",
        "16": "a",
        "17": "t",
        "18": "e",
        "19": "_",
        "20": "l",
        "21": "o",
        "22": "r",
        "23": "e",
        "24": "m",
        "25": "_",
        "26": "i",
        "27": "p",
        "28": "s",
        "29": "u",
        "30": "m",
        "31": " ",
        "32": "a",
        "33": "t",
        "34": " ",
        "35": "0",
        "36": "x",
        "37": "7",
    },
    "(()|trim|list)[INDEX]": {"0": "(", "1": ")"},
    "cycler.__name__[INDEX]": {
        "0": "C",
        "1": "y",
        "2": "c",
        "3": "l",
        "4": "e",
        "5": "r",
    },
    "(xn,)|e|batch(INDEX)|first|last": {
        "1": "(",
        "2": "U",
        "3": "n",
        "4": "d",
        "5": "e",
        "6": "f",
        "7": "i",
        "8": "n",
        "9": "e",
        "10": "d",
        "11": ",",
        "12": ")",
    },
    "((xn,)|e)[INDEX]": {
        "0": "(",
        "1": "U",
        "2": "n",
        "3": "d",
        "4": "e",
        "5": "f",
        "6": "i",
        "7": "n",
        "8": "e",
        "9": "d",
        "10": ",",
        "11": ")",
    },
}
